development:
  adapter: mysql2
  database: findyourmp_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: findyourmp_test
  username: root
  password: 
  socket: /tmp/mysql.sock
    
    
production:
  adapter: mysql2
  database: findyourmp_production
  username: root
  password: 
  socket: /tmp/mysql.sock